version: '3.8'

services:
  # lavinmq:
  #   image: ghcr.io/cloudamqp/lavinmq:latest
  #   container_name: lavinmq
  #   ports:
  #     - "5672:5672"  # AMQP
  #     - "15672:15672" # Web UI
  #   environment:
  #     - LAVINMQ_DEFAULT_USER=guest
  #     - LAVINMQ_DEFAULT_PASS=guest

  # milvus:
  #   image: milvusdb/milvus:v2.3.9
  #   container_name: milvus
  #   ports:
  #     - "19530:19530" # Milvus gRPC
  #     - "9091:9091"   # Milvus HTTP
  #   command: ["milvus", "run", "standalone"]

  publisher:
    build: ./publisher
    container_name: rtsp_publisher
    environment:
      - RTSP_URL=rtsp://user:pass@camera-ip/Streaming/Channels/101
      - LAVINMQ_URL=amqp://guest:guest@lavinmq/
      - QUEUE_NAME=cctv.frames
    depends_on:
      - lavinmq

  processor:
    build: ./processor
    container_name: deepface_processor
    environment:
      - LAVINMQ_URL=amqp://guest:guest@lavinmq/
      - QUEUE_NAME=cctv.frames
      - TELEGRAM_BOT_TOKEN=your_bot_token
      - TELEGRAM_CHAT_ID=your_chat_id
      - MILVUS_HOST=${{MILVUS_HOST}}
      - COLLECTION_NAME=person_embeddings
    depends_on:
      - lavinmq
      - milvus

  streamlit:
    build: ./streamlit_ui
    container_name: streamlit_dashboard
    ports:
      - "8501:8501"
    environment:
      - LAVINMQ_URL=amqp://guest:guest@lavinmq/
      - QUEUE_NAME=cctv.frames
    depends_on:
      - lavinmq
